apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-parameters
data:
  hostname: "localhost"
  port: "3306"
  username: "root"
  password: "root"
  dbname: "exam"

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
type: Opaque
data:
  password: cm9vdA==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-mysql
spec:
  selector:
    matchLabels:
      app: go-mysql
  template:
    metadata:
      labels:
        app: go-mysql
    spec:
      containers:
        - name: go-app
          image: go-k8s:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-parameters
                  key: hostname
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-parameters
                  key: port
            - name: MYSQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-parameters
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-parameters
                  key: password
            - name: MYSQL_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-parameters
                  key: dbname
          ports:
            - containerPort: 1016
        - name: mysql
          image: mysql:8.0.18
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-parameters
                  key: dbname
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: NodePort
  selector:
    app: go-mysql
  ports:
    - name: go-app
      port: 3306
      targetPort: 3306
      nodePort: 30001
